# Generated by Django 3.2.13 on 2022-05-13 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientamount',
            name='amount',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Количество'),
        ),
    ]
