# Generated by Django 3.2.13 on 2022-05-14 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0002_auto_20220514_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='color_hexcode',
            new_name='color',
        ),
        migrations.AlterField(
            model_name='ingredientamount',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_amounts', to='foodgram.ingredient', verbose_name='Ингредиент'),
        ),
    ]
