# Generated by Django 3.2.13 on 2022-05-13 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodgram', '0004_auto_20220513_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foodgram_subscription_following', to=settings.AUTH_USER_MODEL, verbose_name='Автор публикаций'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foodgram_subscription_follower', to=settings.AUTH_USER_MODEL, verbose_name='Подписчик'),
        ),
    ]
