# Generated by Django 3.2.13 on 2022-05-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0006_auto_20220513_1659'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='favouritelist',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_favourite'),
        ),
        migrations.AddConstraint(
            model_name='shoppinglist',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_shopping_item'),
        ),
    ]
