# Generated by Django 3.2.13 on 2022-05-14 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientamount',
            name='author',
        ),
        migrations.RemoveField(
            model_name='ingredientamount',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='ingredientamount',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='ingredientamount',
            name='last_editor',
        ),
    ]
