# Generated by Django 3.2.13 on 2022-05-22 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0003_auto_20220522_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favouritelist',
            name='author',
        ),
        migrations.RemoveField(
            model_name='favouritelist',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='favouritelist',
            name='last_editor',
        ),
        migrations.RemoveField(
            model_name='shoppinglist',
            name='author',
        ),
        migrations.RemoveField(
            model_name='shoppinglist',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='shoppinglist',
            name='last_editor',
        ),
    ]
