# Generated by Django 3.2.13 on 2022-05-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0004_auto_20220518_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='ingredients', through='foodgram.IngredientAmount', to='foodgram.Ingredient', verbose_name='Ингредиенты'),
        ),
    ]
