# Generated by Django 3.2.13 on 2022-05-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0005_auto_20220523_2303'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='favouritelist',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='foodgram_favouritelist_unique'),
        ),
        migrations.AddConstraint(
            model_name='shoppinglist',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='foodgram_shoppinglist_unique'),
        ),
    ]
