# Generated by Django 3.2.13 on 2022-05-23 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0006_auto_20220523_2315'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='unique_following',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='following',
            new_name='author',
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='unique_following'),
        ),
    ]
