name: Foodgram project workflow
on:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
          cd backend/
      - name: Test for PEP8 compliance with flake8 and pytest for Django
        run: |
          python -m flake8

  copy_infra_files_to_server:
    name: Copy docker-compose.yml and nginx.conf to remote server
    runs-on: ubuntu-latest
    needs: tests
    steps:
    - uses: actions/checkout@v2
    - name: Create projects directory
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          sudo rm -rf foodgram/
          mkdir -p foodgram/

    - name: Copy infra files to project directory
      uses: garygrossgarten/github-action-scp@release
      with:
          local: infra/
          remote: /home/${{ secrets.USER }}/foodgram/
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          privateKey: ${{ secrets.SSH_KEY }}

  build_and_push_images_to_docker_hub:
      name: Push Docker images to Docker Hub
      runs-on: ubuntu-latest
      needs: tests
      steps:
        - name: Check out the repo
          uses: actions/checkout@v2

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Login to Docker 
          uses: docker/login-action@v1 
          with:
            username: ${{ secrets.DOCKER_USERNAME }} 
            password: ${{ secrets.DOCKER_PASSWORD }}
            
        - name: Push backend to Docker Hub
          uses: docker/build-push-action@v2 
          with:
            context: ./backend/
            tags: 904863016213768723/foodgram_backend:latest
            push: true
        - name: Push frontend to Docker Hub
          uses: docker/build-push-action@v2 
          with:
            context: ./frontend/
            tags: 904863016213768723/foodgram_frontend:latest
            push: true

  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: [
      build_and_push_images_to_docker_hub,
      copy_infra_files_to_server
    ]
    steps:
    - name: executing remote ssh commands to deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd foodgram/
          rm -rf .env || true
          touch .env
          echo SECRET_KEY=${{ secrets.SECRET_KEY }} >> .env
          echo DB_ENGINE=${{ secrets.DB_ENGINE }} >> .env
          echo POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> .env
          echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env
          echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
          echo DB_HOST=${{ secrets.DB_HOST }} >> .env
          echo DB_PORT=${{ secrets.DB_PORT }} >> .env

          sudo docker-compose stop
          sudo docker-compose rm foodgram_frontend_1
          sudo docker-compose rm foodgram_backend_1
          sudo docker rmi ${{ secrets.DOCKER_USERNAME }}/foodgram_frontend
          sudo docker rmi ${{ secrets.DOCKER_USERNAME }}/foodgram_backend
          sudo docker-compose up -d
  
  send_message:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - name: send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: ${{ github.workflow }} успешно выполнен!
